// Loading Shared Libraries
library identifier: 'my-shared-libraries@demo', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/carlosrodlop/my-jenkins-demos.git'])

// Template Form Validation
strNoSpacesValidator("GitHub Repository Name", "${gh_repo}")
strNoSpacesValidator("Docker Registry", "${d_registry}")

// Building the data object
def configYaml = """---
k8_agent_yaml : '${k8_agent_yaml}'
gh_cred : '${gh_cred}'
gh_repo : '${gh_repo}'
gh_watched_branches : '${gh_watched_branches}'
d_path : '${d_path}'
d_latest : ${d_latest}
d_registry : '${d_registry}'
"""

// Calling the CI Pipeline
mavenK8Project(configYaml)
