pipeline {
    agent {
      // Manage Jenkins > Kubernetes Pod Template 
      label 'maven'
    }
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: "${github_creds}" , url: "${github_repo}"
            }
        }
        stage('Build') {
            container('maven') {
                steps {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
    }
    post {
      // TODO: Add Slack Notification
      success {
        echo 'SUCCESS'
      }
      failure {
        echo 'FAILURE'
      }
    }
}
