/* groovylint-disable CompileStatic */
pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: dind-and-heroku
spec:
  containers:
  - image: "docker:18.06.1-ce-dind"
    name: "dind"
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    env:
    - name: "HEROKU_API_KEY"
      value: "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
    image: "wingrunr21/alpine-heroku-cli:latest"
    name: "heroku"
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
'''
        }
    }
    stages {
        stage('Hello World') {
            steps {
                container('heroku') {
                    sh 'heroku --version'
                }
                container('dind') {
                    sh 'docker info'
                }
            }
        }
    }
}
